# vim: ft=hypr
#

general {
  gaps_in=2
  gaps_out=4
  border_size=2
  col.active_border= $lavender $sapphire 45deg
  #no_border_on_floating = true
  layout = master
  #allow_tearing=true
}

master {
  mfact = 0.6
  allow_small_split = true
  new_on_top = true
  new_status = slave
}


# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
bind = SUPER SHIFT, C, killactive,
bind = SUPER, F, fullscreen,
bind = SUPER, M, fullscreen, 1
bind = SUPER, Space, togglefloating,
bind = SUPER, Space, centerwindow,
bind = SUPER CTRL, Space, hyprexpo:expo, toggle
#bind = SUPER, Space, scroller:toggleoverview
bind = SUPER CTRL, Return, layoutmsg, swapwithmaster auto,
#bind = SUPER CTRL, Return, layoutmsg, focusmaster master,
bind = ALT, Space, layoutmsg, mfact exact 0.95
bind = ALT CTRL, Space, layoutmsg, mfact exact 0.6
bind = SUPER, e, layoutmsg, addmaster
bind = SUPER, q, layoutmsg, removemaster
bind = SUPER, t, workspace, r+1
bind = SUPER, bracketleft, movetoworkspace, r-1
bind = SUPER, bracketright, movetoworkspace, r+1

bind = SUPER CTRL, e, layoutmsg, orientationnext
bind = SUPER CTRL, q, layoutmsg, orientationprev

bind = SUPER, h, movefocus, l
bind = SUPER, h, bringactivetotop
bind = SUPER, l, movefocus, r
bind = SUPER, l, bringactivetotop

bind = SUPER, j, cyclenext, prev
bind = SUPER, j, bringactivetotop
bind = SUPER, k, cyclenext
bind = SUPER, k, bringactivetotop

bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, l, movewindow, r
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, j, movewindow, d

binde = SUPER CTRL, h, resizeactive, -20 0
binde = SUPER CTRL, l, resizeactive, 20 0
binde = SUPER CTRL, k, resizeactive, 0 -20
binde = SUPER CTRL, j, resizeactive, 0 20

binde = SUPER, Up, moveactive, 0 -20
binde = SUPER, Down, moveactive, 0 20
binde = SUPER, Left, moveactive, -20 0
binde = SUPER, Right, moveactive, 20 0


bind = ALT, Tab, layoutmsg, rollnext
bind = ALT SHIFT, Tab, layoutmsg, rollprev

bind = SUPER CTRL SHIFT, M, exec, hyprctl dispatch exit

#====== autogenerated by hyprtheme ======#
#source = ~/.config/hypr/themes/dist/dist.conf
