# vim: ft=hypr
windowrule = float on, match:class file_progress
windowrule = float on, match:class confirm
windowrule = float on, match:class dialog
windowrule = float on, match:class download
windowrule = float on, match:class notification
windowrule = float on, match:class error
windowrule = float on, match:class splash
windowrule = float on, match:class confirmreset
windowrule = float on, match:title Open File
windowrule = float on, match:title branchdialog
windowrule = float on, match:class Lxappearance
windowrule = float on, animation none, stay_focused on, match:class rofi
windowrule = float on, match:class viewnior
windowrule = float on, match:class feh
windowrule = float on, match:class pavucontrol-qt
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class file-roller
windowrule = fullscreen on, match:class wlogout
windowrule = float on, fullscreen on, match:title wlogout
windowrule = idle_inhibit focus, match:class mpv
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, pin on, opacity 1.0 override, match:title ^(Picture-in-Picture)$
windowrule = float on, match:title ^(Bluetooth Devices)$
windowrule = float on, match:title Save As
windowrule = float on, match:title Open Folder
windowrule = float on, size 1280 720, match:class ^(kitty-floating)$
windowrule = border_color 0xfff38ba8, match:float 1
windowrule = border_color 0xffa6e3a2, no_dim on, match:fullscreen 1
windowrule = stay_focused on, match:class swaylock
windowrule = no_anim on, no_focus on, match:class ^(jetbrains-datagrip)$, match:title (win.*)
windowrule = idle_inhibit always, match:title ^(.*[Mm]eet.*)$

windowrule = opacity 1.0 override, match:class mpv-bg
windowrule = no_focus on, border_size 0, match:class ^(mpv-bg)$
#windowrule = noinitialfocus, class:^(mpv-bg)$
#windowrule = float, class:^(mpv-bg)$
#windowrule = maximize, class:^(mpv-bg)$
windowrule = immediate on, idle_inhibit focus, stay_focused on, match:title ^(Assetto Corsa)$
windowrule = float on, match:title ^(Content Manager)$, match:class ^(steam_app_244210)$
windowrule = float on, match:class com.saivert.pwvucontrol

windowrule = float on, match:title ^(Huddle:*)$

windowrule {
  name = focus_rule1
  no_initial_focus = on
  match:initial_class = google-chrome
}

windowrule {
  name = focus_rule2
  no_initial_focus = on
  match:initial_class = kitty
}


# Steam game
windowrule {
  name = steam-app-game
  fullscreen = on
  float = on
  idle_inhibit = focus
  match:class = ^steam_app_\d+$
}

windowrule {
  name = steam-workspace
  workspace = name:S
  match:class = ^steam.*$
}

workspace = name:S, border:false, rounding:false, gapsout:0

windowrule = float on, match:class waydroid.com.mcu.guardingvision

workspace = m[DP-3], layoutopt:orientation:top
